// Lista completa de casas de apostas para uso em todos os filtros e seletores
export const CASAS_APOSTAS = [
  '1pra1',
  '1xbet',
  '4play',
  '4win',
  '5g',
  '6r',
  '7kbet',
  '9d',
  '9f6r',
  'a247',
  'aposta ganha',
  'aposta bet',
  'aposta tudo',
  'aposta1',
  'apostamax',
  'apostaonline',
  'bateubet',
  'baú bingo',
  'bet aki',
  'bet buffalos',
  'bet da sorte',
  'bet do milhão',
  'betcaixa',
  'betcopa',
  'betespecial',
  'betesporte',
  'betfair',
  'betfast',
  'brxbet',
  'bullsbet',
  'caesars',
  'casa de apostas',
  'cassinobet',
  'cbesportes',
  'esportivavip',
  'esportivavet',
  'estrelabet',
  'f12.bet',
  'fanbit',
  'faz o bet',
  'jogo de ouro',
  'jogo online',
  'jonbet',
  'king panda',
  'kto',
  'lance de sorte',
  'nossabet',
  'novibet',
  'oleybet',
  'onabet',
  'onlybets',
  'p9',
  'sportingbet',
  'sportyvip',
  'sportybet',
  'stake',
  'starbet',
  'startbet',
  'vivaro',
  'vivasorte',
  'vs',
  'vupi',
  'wjcasino',
  'zeroum',
  'Afun',
  'AI Bet',
  'Alfa.bet',
  'Apostou.com',
  'Arena Plus',
  'B1 Bet',
  'B2xBet',
  'Bacana Play',
  'BandBet',
  'Bet Bra',
  'Bet Falcons',
  'Bet Fusion',
  'Bet Gorillas',
  'Bet Park',
  'Bet VERA',
  'Bet.Bet',
  'Bet365',
  'Bet4',
  'Betano',
  'Betapp',
  'BetBoom',
  'Betboo',
  'BetMGM',
  'Betnacional',
  'Betou',
  'Betsson',
  'Betwarrior',
  'Betway',
  'Betão',
  'Betmotion',
  'Betsul',
  'Big Bet',
  'Bingo Plus',
  'Blaze',
  'Bolsa De Aposta',
  'BR4BET',
  'BrBet',
  'Brasil dá Sorte',
  'BrasilBet',
  'Bravo.Bet',
  'Brazino777',
  'CassinoPix',
  'CGG Bet',
  'DONALDBET',
  'Donos Da Bola',
  'Energia Bet',
  'Esporte 365',
  'Esportes da Sorte',
  'Esportiva.Bet',
  'Faz O Bet Aí',
  'Faz1 Bet',
  'Flabet',
  'Fogo 777',
  'Fulltbet',
  'GaleraBet',
  'Geral Bet',
  'GINGABET',
  'Gol de Bet',
  'H2 Bet',
  'Hanzbet',
  'Hiper Bet',
  'Kbet',
  'Líderbet',
  'Lotogreen',
  'LotoGreen',
  'Lottoland',
  'Luva.bet',
  'MaxiMaBet',
  'MC Games',
  'Mega Aposta',
  'Megabet',
  'Meridianbet',
  'Mrjack.bet',
  'Multibet',
  'Parimatch',
  'Pinnacle',
  'PixBet',
  'Playuzu',
  'QGBET',
  'Reals',
  'RicoBet',
  'Rivalo',
  'Roobet',
  'Seguro Bet',
  'Sorte Online',
  'Superbet',
  'Suprema Bet',
  'Tele Sena Bet',
  'Tivobet',
  'Tradicional Bet',
  'Upbet',
  'VBet',
  'Vera.Bet',
  'Vertbet',
  'VersusBet',
  'XPbet'
];

